<a href="https://colab.research.google.com/github/abirbhab-dasgupta/word-prediction-lstm/blob/main/LSTM_GRU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [5]:
df = pd.read_csv('qoute_dataset.csv')

In [6]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [7]:
df.shape

(3038, 2)

In [8]:
quotes= df['quote']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [9]:
quotes = quotes.str.lower()

In [10]:
import string
translator = str.maketrans('', '', string.punctuation)
quotes = quotes.apply(lambda x: x.translate(translator))

In [11]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

In [12]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [13]:
vocab_size = 10000
tokenizer = Tokenizer(num_words = vocab_size)
tokenizer.fit_on_texts(quotes)

In [14]:
word_index = tokenizer.word_index
print(len(word_index))
list(word_index.items())[:10]

8978

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [15]:
sequence = tokenizer.texts_to_sequences(quotes)

In [16]:
for i in range(3):
  print(quotes[i])

“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”
“it is our choices harry that show what we truly are far more than our abilities”
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”

In [17]:
for i in range(3):
  print(sequence[i])

[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]
[947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676]
[1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1, 101, 7, 29, 329, 126, 7, 5, 3677]

In [18]:
X=[]
y=[]

for seq in sequence:
  for i in range(1,len(seq)):
    input_seq = seq[:i]
    output_seq = seq[i]
    X.append(input_seq)
    y.append(output_seq)

In [19]:
print(len(X))
print(len(y))

85271
85271

In [20]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [21]:
X_padded = pad_sequences(X,maxlen= max(len(x) for x in X),padding='pre')

In [22]:
X_padded.shape

(85271, 745)

In [23]:
y = np.array(y)

In [24]:
y.shape

(85271,)

In [25]:
from tensorflow.keras.utils import to_categorical

In [26]:
y_one_hot = to_categorical(y, num_classes=vocab_size)
display(y_one_hot.shape)

(85271, 10000)

In [27]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN, LSTM, Dense

In [28]:
embedding_dim = 50
rnn_units = 128

In [29]:
rnn_model = Sequential()
rnn_model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max(len(x) for x in X)))
rnn_model.add(SimpleRNN(units=rnn_units))
rnn_model.add(Dense(units=vocab_size, activation='softmax'))
rnn_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [30]:
lstm_model = Sequential()
lstm_model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max(len(x) for x in X)))
lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size, activation='softmax'))
lstm_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [31]:
epochs = 10
batch_size = 128

In [32]:
history_rnn = rnn_model.fit(X_padded, y_one_hot, epochs=epochs, batch_size=batch_size,validation_split=0.2)

Epoch 1/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 46s 76ms/step - accuracy: 0.0438 - loss: 6.7163 - val_accuracy: 0.0531 - val_loss: 6.6567
Epoch 2/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.0702 - loss: 6.1601 - val_accuracy: 0.0841 - val_loss: 6.4862
Epoch 3/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.0957 - loss: 5.8156 - val_accuracy: 0.0939 - val_loss: 6.4031
Epoch 4/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.1120 - loss: 5.5162 - val_accuracy: 0.1027 - val_loss: 6.4251
Epoch 5/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.1254 - loss: 5.2501 - val_accuracy: 0.1072 - val_loss: 6.4637
Epoch 6/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.1382 - loss: 5.0132 - val_accuracy: 0.1067 - val_loss: 6.5314
Epoch 7/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.1504 - loss: 4.7954 - val_accuracy: 0.1078 - val_loss: 6.5889
Epoch 8/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 67ms/step - accuracy: 0.1648 - loss: 4.5916 - val_accuracy: 0.1063 - val_loss: 6.6752
Epoch 9/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.1832 - loss: 4.4032 - val_accuracy: 0.1055 - val_loss: 6.7650
Epoch 10/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.2034 - loss: 4.2248 - val_accuracy: 0.1073 - val_loss: 6.8341

In [34]:
rnn_model.save('rnn_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [35]:
history_lstm = lstm_model.fit(X_padded, y_one_hot, epochs=100, batch_size=128,validation_split=0.2)

Epoch 1/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 38s 62ms/step - accuracy: 0.0386 - loss: 6.7614 - val_accuracy: 0.0469 - val_loss: 6.7385
Epoch 2/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 55ms/step - accuracy: 0.0548 - loss: 6.3350 - val_accuracy: 0.0632 - val_loss: 6.6647
Epoch 3/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.0736 - loss: 6.0897 - val_accuracy: 0.0822 - val_loss: 6.5584
Epoch 4/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.0925 - loss: 5.8785 - val_accuracy: 0.0905 - val_loss: 6.5249
Epoch 5/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.1039 - loss: 5.7061 - val_accuracy: 0.0960 - val_loss: 6.4973
Epoch 6/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.1145 - loss: 5.5402 - val_accuracy: 0.0987 - val_loss: 6.4980
Epoch 7/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 58ms/step - accuracy: 0.1232 - loss: 5.3811 - val_accuracy: 0.1043 - val_loss: 6.5331
Epoch 8/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.1312 - loss: 5.2329 - val_accuracy: 0.1054 - val_loss: 6.5449
Epoch 9/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.1386 - loss: 5.0926 - val_accuracy: 0.1084 - val_loss: 6.6052
Epoch 10/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 61ms/step - accuracy: 0.1455 - loss: 4.9625 - val_accuracy: 0.1069 - val_loss: 6.6639
Epoch 11/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.1520 - loss: 4.8368 - val_accuracy: 0.1082 - val_loss: 6.7009
Epoch 12/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 58ms/step - accuracy: 0.1596 - loss: 4.7124 - val_accuracy: 0.1105 - val_loss: 6.7599
Epoch 13/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.1672 - loss: 4.5919 - val_accuracy: 0.1098 - val_loss: 6.8245
Epoch 14/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 61ms/step - accuracy: 0.1756 - loss: 4.4737 - val_accuracy: 0.1111 - val_loss: 6.8904
Epoch 15/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.1866 - loss: 4.3568 - val_accuracy: 0.1101 - val_loss: 6.9495
Epoch 16/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 61ms/step - accuracy: 0.1972 - loss: 4.2446 - val_accuracy: 0.1123 - val_loss: 7.0059
Epoch 17/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 39s 57ms/step - accuracy: 0.2096 - loss: 4.1309 - val_accuracy: 0.1095 - val_loss: 7.0722
Epoch 18/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.2243 - loss: 4.0227 - val_accuracy: 0.1101 - val_loss: 7.1505
Epoch 19/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 57ms/step - accuracy: 0.2397 - loss: 3.9176 - val_accuracy: 0.1103 - val_loss: 7.2280
Epoch 20/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.2507 - loss: 3.8195 - val_accuracy: 0.1100 - val_loss: 7.3079
Epoch 21/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 57ms/step - accuracy: 0.2652 - loss: 3.7249 - val_accuracy: 0.1071 - val_loss: 7.3979
Epoch 22/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.2791 - loss: 3.6379 - val_accuracy: 0.1080 - val_loss: 7.4659
Epoch 23/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.2913 - loss: 3.5550 - val_accuracy: 0.1051 - val_loss: 7.5455
Epoch 24/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.3038 - loss: 3.4769 - val_accuracy: 0.1042 - val_loss: 7.6219
Epoch 25/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 61ms/step - accuracy: 0.3143 - loss: 3.4033 - val_accuracy: 0.1045 - val_loss: 7.6908
Epoch 26/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.3268 - loss: 3.3327 - val_accuracy: 0.1027 - val_loss: 7.7674
Epoch 27/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.3374 - loss: 3.2659 - val_accuracy: 0.1033 - val_loss: 7.8338
Epoch 28/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.3484 - loss: 3.2029 - val_accuracy: 0.1017 - val_loss: 7.9183
Epoch 29/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.3578 - loss: 3.1429 - val_accuracy: 0.1027 - val_loss: 7.9898
Epoch 30/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.3679 - loss: 3.0831 - val_accuracy: 0.1008 - val_loss: 8.0654
Epoch 31/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.3772 - loss: 3.0268 - val_accuracy: 0.1003 - val_loss: 8.1362
Epoch 32/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.3874 - loss: 2.9718 - val_accuracy: 0.0998 - val_loss: 8.1937
Epoch 33/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.3956 - loss: 2.9196 - val_accuracy: 0.0971 - val_loss: 8.2572
Epoch 34/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.4047 - loss: 2.8685 - val_accuracy: 0.0984 - val_loss: 8.3414
Epoch 35/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.4138 - loss: 2.8184 - val_accuracy: 0.0996 - val_loss: 8.3945
Epoch 36/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.4213 - loss: 2.7710 - val_accuracy: 0.0965 - val_loss: 8.4720
Epoch 37/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.4282 - loss: 2.7253 - val_accuracy: 0.0973 - val_loss: 8.5250
Epoch 38/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.4377 - loss: 2.6792 - val_accuracy: 0.0976 - val_loss: 8.5819
Epoch 39/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 42s 58ms/step - accuracy: 0.4440 - loss: 2.6362 - val_accuracy: 0.0976 - val_loss: 8.6424
Epoch 40/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.4541 - loss: 2.5927 - val_accuracy: 0.0955 - val_loss: 8.7222
Epoch 41/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.4609 - loss: 2.5509 - val_accuracy: 0.0957 - val_loss: 8.7760
Epoch 42/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.4685 - loss: 2.5103 - val_accuracy: 0.0958 - val_loss: 8.8318
Epoch 43/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.4743 - loss: 2.4718 - val_accuracy: 0.0957 - val_loss: 8.9067
Epoch 44/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.4819 - loss: 2.4335 - val_accuracy: 0.0948 - val_loss: 8.9745
Epoch 45/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.4896 - loss: 2.3953 - val_accuracy: 0.0928 - val_loss: 9.0164
Epoch 46/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.4966 - loss: 2.3584 - val_accuracy: 0.0919 - val_loss: 9.0806
Epoch 47/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.5024 - loss: 2.3232 - val_accuracy: 0.0940 - val_loss: 9.1407
Epoch 48/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.5085 - loss: 2.2884 - val_accuracy: 0.0905 - val_loss: 9.1815
Epoch 49/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.5146 - loss: 2.2554 - val_accuracy: 0.0927 - val_loss: 9.2377
Epoch 50/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.5219 - loss: 2.2219 - val_accuracy: 0.0895 - val_loss: 9.3019
Epoch 51/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 61ms/step - accuracy: 0.5277 - loss: 2.1886 - val_accuracy: 0.0895 - val_loss: 9.3497
Epoch 52/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.5339 - loss: 2.1566 - val_accuracy: 0.0892 - val_loss: 9.4190
Epoch 53/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.5392 - loss: 2.1265 - val_accuracy: 0.0881 - val_loss: 9.4553
Epoch 54/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.5448 - loss: 2.0968 - val_accuracy: 0.0882 - val_loss: 9.5059
Epoch 55/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.5512 - loss: 2.0668 - val_accuracy: 0.0868 - val_loss: 9.5724
Epoch 56/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.5560 - loss: 2.0372 - val_accuracy: 0.0880 - val_loss: 9.6373
Epoch 57/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.5624 - loss: 2.0094 - val_accuracy: 0.0854 - val_loss: 9.6822
Epoch 58/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.5685 - loss: 1.9808 - val_accuracy: 0.0871 - val_loss: 9.7391
Epoch 59/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.5717 - loss: 1.9541 - val_accuracy: 0.0875 - val_loss: 9.8037
Epoch 60/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 57ms/step - accuracy: 0.5795 - loss: 1.9276 - val_accuracy: 0.0860 - val_loss: 9.8337
Epoch 61/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.5838 - loss: 1.9020 - val_accuracy: 0.0847 - val_loss: 9.9057
Epoch 62/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.5878 - loss: 1.8769 - val_accuracy: 0.0861 - val_loss: 9.9684
Epoch 63/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 61ms/step - accuracy: 0.5949 - loss: 1.8521 - val_accuracy: 0.0836 - val_loss: 10.0025
Epoch 64/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.5992 - loss: 1.8266 - val_accuracy: 0.0853 - val_loss: 10.0525
Epoch 65/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 61ms/step - accuracy: 0.6040 - loss: 1.8034 - val_accuracy: 0.0811 - val_loss: 10.1040
Epoch 66/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6088 - loss: 1.7790 - val_accuracy: 0.0849 - val_loss: 10.1687
Epoch 67/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6148 - loss: 1.7556 - val_accuracy: 0.0833 - val_loss: 10.2123
Epoch 68/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6191 - loss: 1.7333 - val_accuracy: 0.0819 - val_loss: 10.2571
Epoch 69/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6230 - loss: 1.7121 - val_accuracy: 0.0842 - val_loss: 10.3292
Epoch 70/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.6270 - loss: 1.6897 - val_accuracy: 0.0814 - val_loss: 10.3801
Epoch 71/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.6315 - loss: 1.6707 - val_accuracy: 0.0819 - val_loss: 10.4285
Epoch 72/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.6360 - loss: 1.6472 - val_accuracy: 0.0824 - val_loss: 10.4779
Epoch 73/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6401 - loss: 1.6296 - val_accuracy: 0.0816 - val_loss: 10.5338
Epoch 74/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.6444 - loss: 1.6098 - val_accuracy: 0.0782 - val_loss: 10.5775
Epoch 75/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6493 - loss: 1.5880 - val_accuracy: 0.0802 - val_loss: 10.6374
Epoch 76/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.6538 - loss: 1.5694 - val_accuracy: 0.0824 - val_loss: 10.6634
Epoch 77/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6572 - loss: 1.5504 - val_accuracy: 0.0799 - val_loss: 10.7311
Epoch 78/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.6611 - loss: 1.5329 - val_accuracy: 0.0811 - val_loss: 10.7535
Epoch 79/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6646 - loss: 1.5134 - val_accuracy: 0.0816 - val_loss: 10.8134
Epoch 80/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6688 - loss: 1.4961 - val_accuracy: 0.0809 - val_loss: 10.8828
Epoch 81/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6730 - loss: 1.4804 - val_accuracy: 0.0809 - val_loss: 10.9044
Epoch 82/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6742 - loss: 1.4638 - val_accuracy: 0.0785 - val_loss: 10.9509
Epoch 83/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.6773 - loss: 1.4462 - val_accuracy: 0.0795 - val_loss: 10.9941
Epoch 84/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6824 - loss: 1.4293 - val_accuracy: 0.0806 - val_loss: 11.0526
Epoch 85/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.6877 - loss: 1.4125 - val_accuracy: 0.0787 - val_loss: 11.1060
Epoch 86/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.6889 - loss: 1.3976 - val_accuracy: 0.0784 - val_loss: 11.1528
Epoch 87/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.6932 - loss: 1.3808 - val_accuracy: 0.0782 - val_loss: 11.1952
Epoch 88/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6976 - loss: 1.3651 - val_accuracy: 0.0777 - val_loss: 11.2371
Epoch 89/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.6998 - loss: 1.3518 - val_accuracy: 0.0789 - val_loss: 11.2944
Epoch 90/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.7035 - loss: 1.3346 - val_accuracy: 0.0772 - val_loss: 11.3191
Epoch 91/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.7057 - loss: 1.3221 - val_accuracy: 0.0765 - val_loss: 11.3792
Epoch 92/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.7080 - loss: 1.3082 - val_accuracy: 0.0789 - val_loss: 11.4235
Epoch 93/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.7121 - loss: 1.2937 - val_accuracy: 0.0778 - val_loss: 11.4708
Epoch 94/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 57ms/step - accuracy: 0.7153 - loss: 1.2799 - val_accuracy: 0.0779 - val_loss: 11.5123
Epoch 95/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.7179 - loss: 1.2657 - val_accuracy: 0.0759 - val_loss: 11.5539
Epoch 96/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.7221 - loss: 1.2523 - val_accuracy: 0.0769 - val_loss: 11.6140
Epoch 97/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.7248 - loss: 1.2393 - val_accuracy: 0.0776 - val_loss: 11.6519
Epoch 98/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.7275 - loss: 1.2261 - val_accuracy: 0.0776 - val_loss: 11.7080
Epoch 99/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.7296 - loss: 1.2142 - val_accuracy: 0.0756 - val_loss: 11.7450
Epoch 100/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.7316 - loss: 1.2028 - val_accuracy: 0.0767 - val_loss: 11.7675

In [36]:
lstm_model.save('lstm_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [41]:
index_to_word = {}
for word, index in word_index.items():
  index_to_word[index] = word

In [42]:
max_len = max(len(x) for x in X)

In [43]:
def predictor(model,tokenizer,text,max_len):
  text = text.lower()

  seq = tokenizer.texts_to_sequences([text])[0]
  seq = pad_sequences([seq], maxlen=max_len, padding='pre')

  pred = model.predict(seq,verbose = 0)
  pred_index = np.argmax(pred)
  return index_to_word[pred_index]

In [48]:
seed_text = "She is"
next_word = predictor(lstm_model,tokenizer,seed_text,max_len)
print(next_word)

the

In [53]:
def generate_text(model,tokenizer,seed_text,max_len,n_words):
  for _ in range(n_words):
    next_word = predictor(model,tokenizer,seed_text,max_len)
    if next_word == "":
      break
    seed_text += " " + next_word
  return seed_text

In [54]:
seed = "are you a "
generate_text = generate_text(lstm_model,tokenizer,seed,max_len,10)
print(generate_text)

are you a  brain life turns it into the light and the past

In [57]:
import pickle
with open("tokenizer.pkl", "wb") as f:
  pickle.dump(tokenizer, f)

In [58]:
with open("max_len.pkl", "wb") as f:
  pickle.dump(max_len, f)